version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - build_files:/app/build
    working_dir: /app
    command: ["npm", "run", "build"]

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://wiciu:qwerty@db:5432/schooldb?schema=public
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - build_files:/usr/share/nginx/html
      - ./nginx/static:/usr/share/nginx/static
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: wiciu
      POSTGRES_PASSWORD: qwerty 
      POSTGRES_DB: schooldb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  build_files:  # Add this line
