services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - build_files:/app/build
    working_dir: /app
    command: ["npm", "run", "build"]

  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}" 
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - build_files:/usr/share/nginx/html
      - ./nginx/static:/usr/share/nginx/static
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  build_files:
