services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=... //dodam se potem
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: //to trzeba ustawić
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 